#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Oct  3 18:20:47 2022

@author: maferv
"""

while True:
    x=input("Enter a number to count")
    if x == 'q' or x=='quit':
        break
    x=int(x)
    y=1
    
    while True:
        print(y)
        y=y+1
        if y>x:
            break